# Project information
site_name: Egedal Kommunes Spildevandsplan
site_author: Center for Teknik og Miljø - Egedal kommune

# Repository
repo_name: 'Egedal-kommune/spildevandsplan'
repo_url: 'https://github.com/Egedal-kommune/spildevandsplan'

# Configuration
theme:
  name: 'material'
  custom_dir: 'custom_theme/'
  logo:
    icon: 'bubble_chart'
  language: 'da'
  favicon: 'img/favicon.ico'

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition

extra:
  version: 2019

dev_addr: 0.0.0.0:8088

# TOC
nav:
  - Indledning: index.md
  - Status: status/index.md
  - Plan: plan/index.md
  - Regler og retningslinjer: regler_retning/index.md
  - Vandmiljø: vandmiljo/index.md
  - Lov og plangrundlag: lov_plan/index.md
  - Bilag: bilag/index.md
  - Ord- og begrebsliste: ord_og_begreb/index.md
