site_name: My Docs

theme:
  name: 'material'
  custom_dir: 'custom_theme/'
  logo:
    icon: 'bubble_chart'
  language: 'da'

extra:
  version: 2019

dev_addr: 0.0.0.0:8000

nav:
  - Indledning: index.md
  - Charts: chart/index.md
  - Maps: maps/index.md
